remove unnecessary % that came from immerda's branch, with it the following errors are caused:
Operator or semicolon missing before %Nsa at /etc/nagios_nsa.cfg line 1.
Ambiguous use of % resolved as operator % at /etc/nagios_nsa.cfg line 1.
ERROR: Failure compiling '/etc/nagios_nsa.cfg' - syntax error at /etc/nagios_nsa.cfg line 1, near "%%Nsa "